// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "The cat REST API",
    "title": "Cat API",
    "version": "1.0.0"
  },
  "paths": {
    "/": {
      "get": {
        "description": "Get all the cats with pagination",
        "produces": [
          "application/json"
        ],
        "tags": [
          "cats"
        ],
        "parameters": [
          {
            "type": "integer",
            "format": "int64",
            "description": "Offset to start from",
            "name": "since",
            "in": "query"
          },
          {
            "type": "integer",
            "format": "int32",
            "default": 20,
            "description": "Maximum results number",
            "name": "limit",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "List of cats",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/cat"
              }
            }
          },
          "500": {
            "description": "internal error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "post": {
        "description": "Create a new cat",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "cats"
        ],
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/cat"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Cat created",
            "schema": {
              "$ref": "#/definitions/cat"
            }
          },
          "400": {
            "description": "bad request",
            "schema": {
              "$ref": "#/definitions/error"
            }
          },
          "500": {
            "description": "internal error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/{id}": {
      "get": {
        "description": "Get a cat by id",
        "produces": [
          "application/json"
        ],
        "tags": [
          "cats"
        ],
        "responses": {
          "200": {
            "description": "Cat found",
            "schema": {
              "$ref": "#/definitions/cat"
            }
          },
          "404": {
            "description": "not found",
            "schema": {
              "$ref": "#/definitions/error"
            }
          },
          "500": {
            "description": "internal error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "put": {
        "description": "Modify a cat by id",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "cats"
        ],
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/cat"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Cat modified",
            "schema": {
              "$ref": "#/definitions/cat"
            }
          },
          "400": {
            "description": "bad request",
            "schema": {
              "$ref": "#/definitions/error"
            }
          },
          "404": {
            "description": "not found",
            "schema": {
              "$ref": "#/definitions/error"
            }
          },
          "500": {
            "description": "internal error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "delete": {
        "description": "Delete a cat by id",
        "produces": [
          "application/json"
        ],
        "tags": [
          "cats"
        ],
        "responses": {
          "204": {
            "description": "Cat deleted"
          },
          "404": {
            "description": "not found",
            "schema": {
              "$ref": "#/definitions/error"
            }
          },
          "500": {
            "description": "internal error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "parameters": [
        {
          "type": "integer",
          "format": "int64",
          "name": "id",
          "in": "path",
          "required": true
        }
      ]
    }
  },
  "definitions": {
    "cat": {
      "type": "object",
      "required": [
        "name",
        "color"
      ],
      "properties": {
        "age": {
          "type": "integer",
          "format": "int32"
        },
        "color": {
          "type": "string",
          "enum": [
            "black",
            "white",
            "ginger",
            "stripped"
          ]
        },
        "created_at": {
          "type": "string",
          "format": "dateTime",
          "readOnly": true
        },
        "feral": {
          "type": "boolean"
        },
        "id": {
          "type": "integer",
          "format": "int64",
          "readOnly": true
        },
        "name": {
          "type": "string",
          "minLength": 2
        }
      }
    },
    "error": {
      "type": "string"
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "The cat REST API",
    "title": "Cat API",
    "version": "1.0.0"
  },
  "paths": {
    "/": {
      "get": {
        "description": "Get all the cats with pagination",
        "produces": [
          "application/json"
        ],
        "tags": [
          "cats"
        ],
        "parameters": [
          {
            "type": "integer",
            "format": "int64",
            "description": "Offset to start from",
            "name": "since",
            "in": "query"
          },
          {
            "type": "integer",
            "format": "int32",
            "default": 20,
            "description": "Maximum results number",
            "name": "limit",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "List of cats",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/cat"
              }
            }
          },
          "500": {
            "description": "internal error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "post": {
        "description": "Create a new cat",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "cats"
        ],
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/cat"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Cat created",
            "schema": {
              "$ref": "#/definitions/cat"
            }
          },
          "400": {
            "description": "bad request",
            "schema": {
              "$ref": "#/definitions/error"
            }
          },
          "500": {
            "description": "internal error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/{id}": {
      "get": {
        "description": "Get a cat by id",
        "produces": [
          "application/json"
        ],
        "tags": [
          "cats"
        ],
        "responses": {
          "200": {
            "description": "Cat found",
            "schema": {
              "$ref": "#/definitions/cat"
            }
          },
          "404": {
            "description": "not found",
            "schema": {
              "$ref": "#/definitions/error"
            }
          },
          "500": {
            "description": "internal error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "put": {
        "description": "Modify a cat by id",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "cats"
        ],
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/cat"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Cat modified",
            "schema": {
              "$ref": "#/definitions/cat"
            }
          },
          "400": {
            "description": "bad request",
            "schema": {
              "$ref": "#/definitions/error"
            }
          },
          "404": {
            "description": "not found",
            "schema": {
              "$ref": "#/definitions/error"
            }
          },
          "500": {
            "description": "internal error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "delete": {
        "description": "Delete a cat by id",
        "produces": [
          "application/json"
        ],
        "tags": [
          "cats"
        ],
        "responses": {
          "204": {
            "description": "Cat deleted"
          },
          "404": {
            "description": "not found",
            "schema": {
              "$ref": "#/definitions/error"
            }
          },
          "500": {
            "description": "internal error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "parameters": [
        {
          "type": "integer",
          "format": "int64",
          "name": "id",
          "in": "path",
          "required": true
        }
      ]
    }
  },
  "definitions": {
    "cat": {
      "type": "object",
      "required": [
        "name",
        "color"
      ],
      "properties": {
        "age": {
          "type": "integer",
          "format": "int32"
        },
        "color": {
          "type": "string",
          "enum": [
            "black",
            "white",
            "ginger",
            "stripped"
          ]
        },
        "created_at": {
          "type": "string",
          "format": "dateTime",
          "readOnly": true
        },
        "feral": {
          "type": "boolean"
        },
        "id": {
          "type": "integer",
          "format": "int64",
          "readOnly": true
        },
        "name": {
          "type": "string",
          "minLength": 2
        }
      }
    },
    "error": {
      "type": "string"
    }
  }
}`))
}
