// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// CatsColumns holds the columns for the "cats" table.
	CatsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "age", Type: field.TypeInt, Nullable: true},
		{Name: "name", Type: field.TypeString, Unique: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "color", Type: field.TypeEnum, Enums: []string{"black", "white", "ginger", "stripped"}},
		{Name: "feral", Type: field.TypeBool, Default: false},
	}
	// CatsTable holds the schema information for the "cats" table.
	CatsTable = &schema.Table{
		Name:       "cats",
		Columns:    CatsColumns,
		PrimaryKey: []*schema.Column{CatsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		CatsTable,
	}
)

func init() {
}
