// Code generated by go-swagger; DO NOT EDIT.

package cats

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"rest_api/swagger/models"
)

// GetIDOKCode is the HTTP code returned for type GetIDOK
const GetIDOKCode int = 200

/*GetIDOK Cat found

swagger:response getIdOK
*/
type GetIDOK struct {

	/*
	  In: Body
	*/
	Payload *models.Cat `json:"body,omitempty"`
}

// NewGetIDOK creates GetIDOK with default headers values
func NewGetIDOK() *GetIDOK {

	return &GetIDOK{}
}

// WithPayload adds the payload to the get Id o k response
func (o *GetIDOK) WithPayload(payload *models.Cat) *GetIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get Id o k response
func (o *GetIDOK) SetPayload(payload *models.Cat) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetIDNotFoundCode is the HTTP code returned for type GetIDNotFound
const GetIDNotFoundCode int = 404

/*GetIDNotFound not found

swagger:response getIdNotFound
*/
type GetIDNotFound struct {

	/*
	  In: Body
	*/
	Payload models.Error `json:"body,omitempty"`
}

// NewGetIDNotFound creates GetIDNotFound with default headers values
func NewGetIDNotFound() *GetIDNotFound {

	return &GetIDNotFound{}
}

// WithPayload adds the payload to the get Id not found response
func (o *GetIDNotFound) WithPayload(payload models.Error) *GetIDNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get Id not found response
func (o *GetIDNotFound) SetPayload(payload models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetIDNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetIDInternalServerErrorCode is the HTTP code returned for type GetIDInternalServerError
const GetIDInternalServerErrorCode int = 500

/*GetIDInternalServerError internal error

swagger:response getIdInternalServerError
*/
type GetIDInternalServerError struct {

	/*
	  In: Body
	*/
	Payload models.Error `json:"body,omitempty"`
}

// NewGetIDInternalServerError creates GetIDInternalServerError with default headers values
func NewGetIDInternalServerError() *GetIDInternalServerError {

	return &GetIDInternalServerError{}
}

// WithPayload adds the payload to the get Id internal server error response
func (o *GetIDInternalServerError) WithPayload(payload models.Error) *GetIDInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get Id internal server error response
func (o *GetIDInternalServerError) SetPayload(payload models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetIDInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
