// Code generated by go-swagger; DO NOT EDIT.

package cats

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"rest_api/swagger/models"
)

// PostCreatedCode is the HTTP code returned for type PostCreated
const PostCreatedCode int = 201

/*PostCreated Cat created

swagger:response postCreated
*/
type PostCreated struct {

	/*
	  In: Body
	*/
	Payload *models.Cat `json:"body,omitempty"`
}

// NewPostCreated creates PostCreated with default headers values
func NewPostCreated() *PostCreated {

	return &PostCreated{}
}

// WithPayload adds the payload to the post created response
func (o *PostCreated) WithPayload(payload *models.Cat) *PostCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post created response
func (o *PostCreated) SetPayload(payload *models.Cat) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostBadRequestCode is the HTTP code returned for type PostBadRequest
const PostBadRequestCode int = 400

/*PostBadRequest bad request

swagger:response postBadRequest
*/
type PostBadRequest struct {

	/*
	  In: Body
	*/
	Payload models.Error `json:"body,omitempty"`
}

// NewPostBadRequest creates PostBadRequest with default headers values
func NewPostBadRequest() *PostBadRequest {

	return &PostBadRequest{}
}

// WithPayload adds the payload to the post bad request response
func (o *PostBadRequest) WithPayload(payload models.Error) *PostBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post bad request response
func (o *PostBadRequest) SetPayload(payload models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// PostInternalServerErrorCode is the HTTP code returned for type PostInternalServerError
const PostInternalServerErrorCode int = 500

/*PostInternalServerError internal error

swagger:response postInternalServerError
*/
type PostInternalServerError struct {

	/*
	  In: Body
	*/
	Payload models.Error `json:"body,omitempty"`
}

// NewPostInternalServerError creates PostInternalServerError with default headers values
func NewPostInternalServerError() *PostInternalServerError {

	return &PostInternalServerError{}
}

// WithPayload adds the payload to the post internal server error response
func (o *PostInternalServerError) WithPayload(payload models.Error) *PostInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post internal server error response
func (o *PostInternalServerError) SetPayload(payload models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
