// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"log"

	"rest_api/ent/migrate"

	"rest_api/ent/cat"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// Cat is the client for interacting with the Cat builders.
	Cat *CatClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	cfg := config{log: log.Println, hooks: &hooks{}}
	cfg.options(opts...)
	client := &Client{config: cfg}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.Cat = NewCatClient(c.config)
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, fmt.Errorf("ent: cannot start a transaction within a transaction")
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:    ctx,
		config: cfg,
		Cat:    NewCatClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, fmt.Errorf("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		config: cfg,
		Cat:    NewCatClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		Cat.
//		Query().
//		Count(ctx)
//
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.Cat.Use(hooks...)
}

// CatClient is a client for the Cat schema.
type CatClient struct {
	config
}

// NewCatClient returns a client for the Cat from the given config.
func NewCatClient(c config) *CatClient {
	return &CatClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `cat.Hooks(f(g(h())))`.
func (c *CatClient) Use(hooks ...Hook) {
	c.hooks.Cat = append(c.hooks.Cat, hooks...)
}

// Create returns a create builder for Cat.
func (c *CatClient) Create() *CatCreate {
	mutation := newCatMutation(c.config, OpCreate)
	return &CatCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Cat entities.
func (c *CatClient) CreateBulk(builders ...*CatCreate) *CatCreateBulk {
	return &CatCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Cat.
func (c *CatClient) Update() *CatUpdate {
	mutation := newCatMutation(c.config, OpUpdate)
	return &CatUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *CatClient) UpdateOne(ca *Cat) *CatUpdateOne {
	mutation := newCatMutation(c.config, OpUpdateOne, withCat(ca))
	return &CatUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *CatClient) UpdateOneID(id int) *CatUpdateOne {
	mutation := newCatMutation(c.config, OpUpdateOne, withCatID(id))
	return &CatUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Cat.
func (c *CatClient) Delete() *CatDelete {
	mutation := newCatMutation(c.config, OpDelete)
	return &CatDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a delete builder for the given entity.
func (c *CatClient) DeleteOne(ca *Cat) *CatDeleteOne {
	return c.DeleteOneID(ca.ID)
}

// DeleteOneID returns a delete builder for the given id.
func (c *CatClient) DeleteOneID(id int) *CatDeleteOne {
	builder := c.Delete().Where(cat.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &CatDeleteOne{builder}
}

// Query returns a query builder for Cat.
func (c *CatClient) Query() *CatQuery {
	return &CatQuery{
		config: c.config,
	}
}

// Get returns a Cat entity by its id.
func (c *CatClient) Get(ctx context.Context, id int) (*Cat, error) {
	return c.Query().Where(cat.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *CatClient) GetX(ctx context.Context, id int) *Cat {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *CatClient) Hooks() []Hook {
	return c.hooks.Cat
}
