// Code generated by entc, DO NOT EDIT.

package ent

import (
	"rest_api/ent/cat"
	"rest_api/ent/schema"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	catFields := schema.Cat{}.Fields()
	_ = catFields
	// catDescAge is the schema descriptor for age field.
	catDescAge := catFields[0].Descriptor()
	// cat.AgeValidator is a validator for the "age" field. It is called by the builders before save.
	cat.AgeValidator = catDescAge.Validators[0].(func(int) error)
	// catDescCreatedAt is the schema descriptor for created_at field.
	catDescCreatedAt := catFields[2].Descriptor()
	// cat.DefaultCreatedAt holds the default value on creation for the created_at field.
	cat.DefaultCreatedAt = catDescCreatedAt.Default.(func() time.Time)
	// catDescFeral is the schema descriptor for feral field.
	catDescFeral := catFields[4].Descriptor()
	// cat.DefaultFeral holds the default value on creation for the feral field.
	cat.DefaultFeral = catDescFeral.Default.(bool)
}
